# This is a basic workflow to help you get started with Actions

name: NEU CourseTable Email Bot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install lib'
        run: pip install lxml && pip install ics
      - name: 'Working'
        run: python main.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com 
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: test
          body: file://mail.md
          to: ${{ secrets.EMAIL_ADDR }}
          from: GitHub Actions
          content_type: text/plain
          attachments: ./my.ics
